### ISSUE TITLE
AR/Sequel integration?

### ISSUE THREAD

**Issue by aemadrid** [tomekw/hucpa#2]
Looks very interesting. Just wondering if you've investigated how to integrate with ActiveRecord or Sequel.

**Comment by tomekw** [comment]
@aemadrid TBH - not yet, but this one of my goals.

Unfortunately it looks like I've messed up something with `$LOAD_PATH` and version `0.2.0` is unusable actually (have you tried it as a lib?). Working on a fix...

**Comment by tomekw** [comment]
I hope it answers your question :)

**Comment by aemadrid** [comment]
Thanks for the info. I haven't tried using it yet but I'll give it a try.

**Comment by tomekw** [comment]
@aemadrid you may want to try https://github.com/tomekw/jdbc ! I think it's a great start.

**Comment by aemadrid** [comment]
cool, thx!
